### PR TITLE
Added experimental MQTT to firmware

### PR DESCRIPTION
**Pull request by steffanlm**
Added PubSubClient library and hardcoded setup for MQTT broker PayloadData should most likely be longer, havent tested length in line 59 @ NES-MEP-UI Added 5 second MQTT push in line 221-223 @ NES-MEP-UI Added MQTT keep alive at line 228 @ NES-MEP-UI
Added MqttSetup and MqttSensorHomeAssistantAutoDisoverySetup functions

I'm not able to test the code, but the concept should be working as it's quite simple - but I might be wrong.

And yes, trying to contribute for my first time :)

### CODE REVIEW

**Comment by glynge** [comment]
Hi Stefanlm
Thanks for contributing - this is functionality we really want to provide.
Unfortunately, we need the setup to be configurable on the setup page as we don't require people to compile their own binaries.
Also, I need someone to test this before I can merge it, because I currently have no MQTT broker installed - so I can't test it. We need to test it because we want to avoid bricking a lot of modules already out there... 
I hope you understand that I want to be careful about this and why we need some time before merging this.
I'll for sure look into this later on when time permits.

**Comment by steffanlm** [comment]
Updated all the code and ensured no issues with compiling. Not having a spare ESP32 or the MEP key yet, to flash and ensure it's 100% functioning. Can you possibly try one out with current commits?
image

**Comment by glynge** [comment]
Hi Stefanlm
I'm preparing a new batch of 17 MEP modules this weekend - still need the last component but will try to bring the modules to a state where I only need to add that when it arrives.
So I'll be quite occupied soldering and I need to keep this a priority as some has been waiting for a month now...
Next weekend I have a major ERP upgrade at my workplace (will work Sunday 6am - 17pm if not longer), so unfortunately, I don't think I'll manage to test any of this the next two weeks. I'm sorry for that, but sometimes you get caught up by real world/life :-).
This does not mean that we don't appreciate your effort or contribution - this is a big wish of ours (to get more people involved). We are just lacking spare time for this project right now...
I will for sure get around to test this and as soon as I'm sure we are not bricking any modules (preventing them from upgrade/downgrade) I'll include your contribution in the main version!
Again - thank you for your effort and contribution to this project!
Best regards,
Gert Lynge, gert@dabbler.dk

**Comment by steffanlm** [comment]
Hi Gert,
Thats completely understandable :) Hence it will be possible to get more contributors with more boards out :)
I'll wait around, hoping to get the key soon so I can test out the code on my own. 
Just added more options to disabling MQTT and Hass auto discovery, which I assumed would be useable.
Best regards,
Steffan

**Comment by Riiiiiiis** [comment]
Hi @steffanlm I've just installed a module and would like to get mqtt working. I know about the mqtt part, and have used Arduino IDE for small projects for years - but have never really used github. How do I get a build with your updates?
-Christian

**Comment by ZeppDK** [comment]
Im also up for compiling to get mqtt working so i can get it into my smarthome 🙂

**Comment by steffanlm** [comment]
To be honest, I haven't uploaded the code yet to my own board, due to private circumstances, that have taken my entire focus the last months.
I'm using Arduino IDE to program and compile the files. Would think you will need to compile a file, that can be uploaded either via the web interface or maybe, if in luck, through Arduino IDEs own OTA interface.
In Github you can just go to my fork, and download the files via the green " <> Code" button as .zip. But please take note, that I haven't tested the code on my own board or can give any assurances as of now.

**Comment by mist1971** [comment]
Hej,

 Let me start out by saying that I have no skills at all in GitHub, but I managed to created an account and copy the code steffanlm made to my machine. To share what I have done with you I have dragged it to this field in the zip file.

I made a few modifications to the code - mainly because there is a max limit of 255 characters on the payload.
The code is in this zip-file:
[MEP-SW-ESP32-mqtt_dev.zip](https://github.com/DabblerDK/MEP-SW-ESP32/files/10304823/MEP-SW-ESP32-mqtt_dev.zip)

I send them to Home Assistant you can see the values in MQTT Explorer in this screen shot:
image

In order to get the sensors into Home assistant the yaml in the following text file should be pasted to the mqtt sensor section of your configuration.yaml files:
[configuration_yaml_mqtt_sensor_section.txt](https://github.com/DabblerDK/MEP-SW-ESP32/files/10304828/configuration_yaml_mqtt_sensor_section.txt)

I have not created an Home Assistant sensor for each of the data fields in the MQTT, but it should be fairly easy to add the remaining sensors if someone is interested in them.

**Comment by steffanlm** [comment]
Hi Mist,
Is it any way possible to point me to the code changes you have made? Will implement it into the code I have here.
Can you confirm, that the MQTT part works fine, with your code changes?
In the code, you have updated, theres a possibility to autodiscover, so you won't need to add the sensors manually - have I forgot some of the sensors in the autodiscovery part?
Best regards
Steffan

**Comment by mist1971** [comment]
Hi,
 The changes are mainly in the function MqttReadSendSensorData() - I have it in the main.cpp file because I prefer to use PlatformIO instead of the Arduino environment.
 I added a few signals to the ConsumptionData struct, but you can just delete those.
 Yes, I have it running with that code, and the values are updated in Home Assistant.

 I am not a fan of autodiscover, so I focused on getting the data to home assistant.
 If you haven't tested that either, I would probably suggest adding a big disclaimer so people don't risk ending up in
 a situation where they will need to get the print out of the electricity meter, moving jumpers, and a FTDI232 to program the chip on the print.

 You can just load it on an ESP32, and see if it shows up in home assistant navigating to settings->integration->configure the mosquito broker. Naturally you won't be able to see the values, but if it does not work in this way it will 100% sure not work when you put the binary on the print.

Best Regards,
Michael

**Comment by mist1971** [comment]
line 109 in main must be:
  mqtt_enable = preferences.getBool("mqtt_enable",false);

If not it wil not work, when upgrading from the original Dabbler firmware

**Comment by steffanlm** [comment]
Hi Michael,
Not that much of a coder myself - doing enthusiast stuff only :)
You are probably way more competent in coding, so I won't delete anything, should be a community that adds up, not holding back.
Only "stopped" implementing, as there didn't seem to be much interest of testing out a few months ago. Have got a spare ESP32 in the meantime, that I will try it on - but it would be really cool, if the code somhow could be merged more smoothly using GitHub - think that you will need to forge mine, and submit changes, which will then be updated in my fork, when I accept?

Btw added disclaimer in header - thats a shame everything gets copied right over, when you do fork :(

mqtt_enable = preferences.getBool("mqtt_enable",false); <-- was already changed, mistake it wasn't uploaded to Git already.

Will try and implement as many changes you added as possible, and reupload on Git.

Best regards 
Steffan

**Comment by mist1971** [comment]
I use to work as a programmer :) but I have not coded at work for a number of years. We never used GIT, so I don't know how that works, but I am familiar with other code revision systems so I should probably just roll-up my sleves and figure out how to do this in a more official way.

The following was committed in your code - I changed it to true while debugging and forgot to switch it back.
mqtt_enable = preferences.getBool("mqtt_enable",false);

The problem with it being true is that it makes the board crash - my brother now have a "brick" that doesn't work.
Worst case we need the programmer on the print, so it is not the end of the world - I think I can think of a work around so it is not needed. I will start testing that now.

My plan for Christmas was to add MQTT to the software. I saw you code, and it was mostly implemented but I spotted fairly fast that a bit of testing was needed :)    While coding a bit for my heatmeter (varmemåler) I stumpled on the same 255 char limitation in Home Assistant - I think it is a Home Assistant limitation as MQTT seem to accept much longer strings, but I am not going to fight the HA developers as there is a fairly simple and somewhat acceptable work around.
Like I said above I am not a big fan of the creating sensors from software, so I will not debug the MQTT-create part.

**Comment by mist1971** [comment]
After making "brick" out of my brothers print I spotted two major issues in MQTTSetup and MQTTReconnect.
The while loops basically means that it is impossible to upload new firmware to the ESP or access the configure page in case MQTT information that does not allow you to logon to the MQTT broker is specified.
This is a BLOCKER - so do not upload try to upload the previous zip file.

I believe it is corrected in the following zip file - at least I can now specify wrong information, and still access the web-files that allow me to upload new firmware or change the configuration.

[MEP-SW-ESP32-mqtt_dev_mqttenableFalse_while_in_MQTTSetup_and_MQTTReconnect_ChangedToIf.zip](https://github.com/DabblerDK/MEP-SW-ESP32/files/10315879/MEP-SW-ESP32-mqtt_dev_mqttenableFalse_while_in_MQTTSetup_and_MQTTReconnect_ChangedToIf.zip)

**Comment by steffanlm** [comment]
The file you sent, just did hit Windows internal limit on characters, when trying to extract ;) Not a problem though.
Tinkering is about breaking boards - and use FTDI/CP serial connectors to recover from time to time :)

Added break statements on both MqttSetup and MqttReconnect, can see MqttReconnect had a return function, geeze, that code has survived flawlessly the past 5 years on all my homemade sensors, so never paid any attention to that piece of code - basicly been using it headlessly.

**Comment by glynge** [comment]
> After making "brick" out of my brothers print...

Hi mist1971,
If you don't have access to an in circuit programmer (USB FTDI232) that provides 3.3v (please double check that, not all of them will do that - even when configured for 3.3v), fell free to return the module to me.
I'll then reprogram it and return it to you.
(this is NOT something I can do for everyone, but because you tested this MQTT software, I'll be happy to help you out).
If you reprogram it yourself, follow the guides in the readme.md files.

**Comment by Pangel71** [comment]
Hi.

I have tried the new MQTT-version, but without luck.
The project compiles fine and the code uploades. I configured a "1" in MQTT-setup and an IP in Server. I did not put anything in username and password.
I checked "ElectricityMeter/" on my MQTT-broker, but nothing is coming in.
Could you point me at something I can check?

Thanks.

**Comment by mist1971** [comment]
Hi Pangel71,
 The code needs a change for now it can only connect with username and password.
 I will have a look at it to make it more generic, so it can handle the situation with and without user name.

**Comment by mist1971** [comment]
Hi,
 I have made a fork to my GitHub account in the mqtt_dev branch I have updated the code so it can connect without credential.
 It is tested with the mosquitto broker on windows.
 
image

I have decided to remove the binaries, as this is experimental code so you need to know what you are doing before uploading it.

I have only touched the UI code, so I have no idea about the SPIFF code.

**Comment by steffanlm** [comment]
Hi Mist,
I was just browsing your solution, and it looks like the updated code hasn't been uploaded to Git? <-- nevermind, worked when I got the the mqtt_dev branch :)
When you change in your rep, you should also be able to "commit" change to my fork, so the Dabblers can get all the changes to the main fork.
I'm not that skilled in Git, which annoys me - and I'm not sure how we contributes the most efficient way :)
The code is looking into an empty string from the html interface/saved information, which just should be "Null" for the PubSubClient to login without user/password - supposedly it's the change you have made? :)

Happy new year everyone.
Best regards
SteffanLM

**Comment by Riiiiiiis** [comment]
Happy New Year as well

I'm happy to follow the progress, but unfortunately the MEP module I have is now installed 100km from my location, so I can't easily test.

**Comment by Pangel71** [comment]
Hi mist1971.

I am as steffanlm commented not able to find your changes.
I have also found out I am not able to disable the MQTT by putting in "0". This setting is not saved.

Thanks.

**Comment by mist1971** [comment]
I am learning GitHub, and made a pull request....

you should be able to find them here:
https://github.com/mist1971/MEP-SW-ESP32mqtt/tree/mqtt_dev

it seems like not much of this has been tested.
steffanlm have you tested any of your proposed changes?

**Comment by Pangel71** [comment]
Hi.

I have now compiled and uploaded the code and it seems to be working.
Maybe it could be an idea to make the topic configurable?
Right now it is: "ESP32-MEP-Dabbler".

Thanks for all your help.

**Comment by steffanlm** [comment]
@mist1971 I can unfortunately confirm, that I haven't been able to test the code myself, in the beginning due to not having the board, and afterwards due to a large surgery I got carried out in the begnning og december, which keeps me pretty occupied with doctors and hospitals - and also haven't found a way to upload SPIFF with Arduino IDE 2.0+, though I maybe should try with a lower version.
In the "original" mqtt_dev there wasn't added that much code - and I was hoping to put all the "new" MQTT stuff into a new file, to keep all or atleast most of the changes into a single file, easier to test and maintain. But seemed impossible with the current code structure.
A configurable topic would be the a breeze to introduce, it's just the "devicename", that needs to be read from the register, and with a little html in the spiff that needs to be done - exactly the same as the other MQTT variables.

**Comment by glynge** [comment]
Hi @steffanlm 

Just some hints if you are not aware of it:
If it is the web-files you need to upload to the SPIFFS, you can use the recovery page or the regular upload page.
They need to be combined into a single update.wwws file (our own "format", but the folder have a Generate_wwws-script to do that. When uploaded the software will extract the files and store them on the ESP32 SPIFFS.
We currently only support text-files...
Note: The recover-page also have a format SPIFFS partition button if you need to start over.

I have somewhere on a to-do that I'll split all the software functionality into separate files with their own setup- and loop-functions. I'll probably get to it when I'm out of components for hardware sometime in the near future :-). That will probably make it easier to navigate and extend the source code.

**Comment by steffanlm** [comment]
Hi @glynge 
I'm getting my head around it as we speak. It works well with the recovery page, as Arduino IDE doesn't seem to like to re-upload to SPIFF.
Testing the code - the best I've learned (inputting valid and invalid information in the web part), and not getting any errors or crashing code. Still on a bare ESP32 for now.
That would be really cool with the code split - can see, that you are using the code on a whole another level, then I'm used to :) So I screwed up trying to move all MQTT related into one file, as I didn't fully understand how to correctly "link" the data between modules.

How many boards do you have left? :)

**Comment by glynge** [comment]
Hi @steffanlm 
Only a few - most of them is SMD, but I still lack components to finish them. Hopefully they'll araive soon.
But demand seems to have decreased a lot, so hopefully I can re-start work on the software soon.

**Comment by steffanlm** [comment]
Hi @glynge thats a shame that demand have decreased - but if you have been on your back to get it done, it could be good to get some time for other things :) Would be cool with the software, as theres tons of opportunities for the smart home people, which also may raise demand :) 

@mist1971 I have "tested" the code, the best I can. Ensured everything could compile, run and not stalling or crashing. More deep testing are above my skills - though I can handle quite a bit troubleshooting and fix it, if a error should occur.

@Pangel71 MQTT topic can now be changed as you wish :)

Now officially running the mqtt_dev branch on my meter. Every 10th second a nice MQTT packet arrive and it seems to be quite stable for now.

"New" setup added this part:
image
MQTT packages:
image

**Comment by mist1971** [comment]
That sounds good.
I have been running the MQTT part since December 26th, there has not been any hick-ups in MQTT communication during that period of time.

**Comment by hemandk** [comment]
I would like to give this MQTT branch a go and do some testing, but how do I get the bin and wmms file?

**Comment by steffanlm** [comment]
Hi @hemandk 
You can download the [update.wwws](https://github.com/steffanlm/MEP-SW-ESP32/blob/mqtt_dev/NES-MEP-UI-SPIFFS/update.wwws)
And I've added a precompiled .bin file here: [NES-MEP-UI.ino.bin](https://github.com/steffanlm/MEP-SW-ESP32/blob/mqtt_dev/NES-MEP-UI/bin/NES-MEP-UI.ino.bin)

That should be about it - but please take note, this is not the official firmware for the dabbler.dk MEP card.
As it's a "community" build, I encourage that you somehow know how or can get help to get the board back up and running, of something goes wrong with the update to the unofficial version :)

**Comment by hemandk** [comment]
> Hi @hemandk You can download the [update.wwws](https://github.com/steffanlm/MEP-SW-ESP32/blob/mqtt_dev/NES-MEP-UI-SPIFFS/update.wwws) And I've added a precompiled .bin file here: [NES-MEP-UI.ino.bin](https://github.com/steffanlm/MEP-SW-ESP32/blob/mqtt_dev/NES-MEP-UI/bin/NES-MEP-UI.ino.bin)
> 
> That should be about it - but please take note, this is not the official firmware for the dabbler.dk MEP card. As it's a "community" build, I encourage that you somehow know how or can get help to get the board back up and running, of something goes wrong with the update to the unofficial version :)

Board is in my summerhouse, but if it fails I can get access to it next time i'm there :)

**Comment by glynge** [comment]
Hi @hemanddk and @steffanlm 

I'm pretty sure the community is more capable than we are in creating software for this module :-).

That said - bugs can creep in, so I'll suggest that EVERYONE tinkering a lot with the MEP module software gets a FTDI USB programmer for in-circuit flashing of the ESP32.
That way you can recover from "bad" software that makes it impossible to update through the recovery and/or update page. You can start the ESP32 module from scratch with such a programmer - and the readme.md on the GitHub should have information on how to do it - otherwise please ask so we can improve it.

Also PLEASE MAKE SURE that the FTDI USB programmer you choose does provide 3.3v power and NOT 5v power (even some of those with a 3.3v jumper still does it wrong). WARNING: 5v WILL FRY your ESP32.
The J5 on the PCB is made for such a module and the pads are arranged so you can just insert the pins into the PCB. Soldering is not required if you tilt the module a bit with a finger while flashing. Also make sure to connect it correctly: The square solder pad on J5 is GND.

We are using this FTDI USB programmer: https://www.ebay.com/itm/221919994773

Hint: The FTDI USB module is also good for debugging the software. We log a lot of debug stuff to that serial interface... Personally I dont use it for debugging as I have a Raspberry PI permanently connected via wires to my MEP module. This way I can ssh to the Raspberry (my "office" is NOT in the same room as my meter), start a terminal program and see the debug info. from the MEP module...

**Comment by hemandk** [comment]
Pretty sure I have an FTDI USB laying around somewhere, from last time I was playing around with ESP32.

However MQTT is up now and my Total energy sensor is working perfectly sofar. Will add it as a gas sensor and see how it is running.
image

**Comment by steffanlm** [comment]
@hemandk great to see and hear it works out :)

Next step must be to make the webpage more convenient to use - as the "0/1" thing just plain suck as a UI, but to read out the current state and make it "ticked" or not, is not a thing I've tried with the current webserver. Been using a 8266 webserver before, where you build up a large string before sending a response, so everything could easily be made dynamic - maybe I should start to learn more about the webserver used here :)

**Comment by hemandk** [comment]
> @hemandk great to see and hear it works out :)
> 
> Next step must be to make the webpage more convenient to use - as the "0/1" thing just plain suck as a UI, but to read out the current state and make it "ticked" or not, is not a thing I've tried with the current webserver. Been using a 8266 webserver before, where you build up a large string before sending a response, so everything could easily be made dynamic - maybe I should start to learn more about the webserver used here :)

Yeah I had to remember how to make MQTT sensors again.

I think the 0/1 is fine, but maybe make a seperate mqtt tab/link and maybe add some info about the topics that it post out.

Would also be nice to be able to disable that other way Dabbler pushed sensor information to HA when MQTT is enabled.

**Comment by steffanlm** [comment]
@hemandk I've added some more information regarding the topic and added Last Wish. 
Screwed up, as I OTA the changes directly to the MEP, and it wasn't properly tested, so it went into a reboot loop as the MQTT LWT was in a wrong format. The .bin file has been offline tested on another ESP32 and the bug has been removed :)
It seems that neither of my USB to Serial stuff are working, so now I'll wait till i receive some new or find one working in some of my boxes. 

Regarding disabling the normal "API", I would say its up to @glynge to decide what to do - it's not data thats pushed to HA - its merely data HA is pulling from the MEP.

**Comment by hemandk** [comment]
> @hemandk I've added some more information regarding the topic and added Last Wish. Screwed up, as I OTA the changes directly to the MEP, and it wasn't properly tested, so it went into a reboot loop as the MQTT LWT was in a wrong format. The .bin file has been offline tested on another ESP32 and the bug has been removed :) It seems that neither of my USB to Serial stuff are working, so now I'll wait till i receive some new or find one working in some of my boxes.
> 
> Regarding disabling the normal "API", I would say its up to @glynge to decide what to do - it's not data thats pushed to HA - its merely data HA is pulling from the MEP.

Ahh ok but then i can just uninstall the dabbler  integration and just have the mqtt. 

I Will try out the new version tomorrow, did you make a new bin file?

**Comment by steffanlm** [comment]
Yes, theres an updated .bin file in the /bin folder.

**Comment by ZeppDK** [comment]
wow, looking nice... just flashed the new bin file and the www to my board, and i think its perfect having both the "old" connection to HA, and having MQTT running on the side... as i use another smarthome as my main smarthome, but have HA for playing around :-)

**Comment by hemandk** [comment]
Just updated and running nicely. I decided to disable the dabbler integration for now and just run with mqtt.

How is the LWT suppose to work, meaning does it push out status once in a while or only when there is a change in the status?

**Comment by hemandk** [comment]
I think there is something about the LWT sensor that is not working correctly. Mine is showing offline, but actually it online and still sending data.

**Comment by steffanlm** [comment]
@hemandk I've just added a "retain" flag for the "Online" part, as it was for Offline. 
.bin file is updated aswell.

Please post if you find other things you see not functioning as you think it should :)

**Comment by hemandk** [comment]
> @hemandk I've just added a "retain" flag for the "Online" part, as it was for Offline. .bin file is updated aswell.
> 
> Please post if you find other things you see not functioning as you think it should :)

Will do.

Did you consider to make the sensors discoverable with home assistant?

Edit: new firmware is up and running and lwt is working as it should.

**Comment by steffanlm** [comment]
I had created alot of code for Home Assistant Auto Discovery, but decided to ensure the regular code would work solid first. I didn't have any test-bed when I first implemented it.
As of right now, I don't have plans for re-creating the possibilty to use Auto discovery - but if theres a demand, I might look into it again :)

Great that LWT also works perfectly :)

**Comment by glynge** [comment]
Hi @steffanlm 
> Regarding disabling the normal "API", I would say its up to @glynge to decide what to do - it's not data thats pushed to HA - its merely data HA is pulling from the MEP.

I'm not quite sure what the "normal API" is here?
If it is the HA integration, It was not done by us, but by Jan Nielsen.
See [https://www.dabbler.dk/index.php/2022/02/20/guest-writer-echelon-nes-smart-meters-home-assistant-integration/](https://www.dabbler.dk/index.php/2022/02/20/guest-writer-echelon-nes-smart-meters-home-assistant-integration/)
He built it on top of the webservice we provide - but that webservice is also used by the built in Dashboard page, so if you want the Dashboard to work, the webservice need to work too... Jan Nielsen did not add anything to the module firmware.

Again: Thanks to everyone for providing this MQTT support!

**Comment by steffanlm** [comment]
Hi @glynge 
It's exactly the webservice you mention, that i was referring to. And as you state, it's used for more than the Home Assistant integration, and should not be altered anyhow :)
Good night.

**Comment by rhessell** [comment]
Hi,

I just tested this version but ended up compiling it before I noticed there was a binary. I had to go through the source code to find out that I also needed to upload the web files to configure MQTT, but it will be solved if it's included in the release version.

MQTT seems to be working and appears to be somewhat stable based on a few hours of testing. However, if the intention was for it to support autodiscovery on home-assistant, either I'm doing something wrong or that part isn't working.

**Comment by rhessell** [comment]
An it would be a good idea to leave a comment in the source code that the PubSubClient lib is needed.

**Comment by steffanlm** [comment]
I've updated the readme, to reflect that it's needed to use the PubSubClient library.
I just noticed, that the MQTT integration continues to send latest meter data, when the Home Assistant integration stop receiving data. http://10.0.1.150/getDashDataWS is still updating values.
At the moment I'm working on the Home Assistant Auto discovery :)

**Pull request merged**
